### ISSUE TITLE
07版本，存档排序错误问题

### ISSUE THREAD

**Issue by GoogleCodeExporter** [javascriptextjs/micolog#32]
```
存档最后出来的排序结果不正确，
原因是 Archive 的 date 
属性没有被赋值过，它的值永远是当前时间，所以排出来的
结果不正常。

我现在的处理方法是
在 model.py 文件的 update_archive 函数中
self.monthyear = my
改为
self.monthyear = my
archive.date = self.date
这样排序就正常了。

这样改不知道是不是合理，我的 python 还是这两天为了改 
micolog 学的。
```

Original issue reported on code.google.com by `snailb...@gmail.com` on 15 Jan 2010 at 7:48

**Comment by GoogleCodeExporter** [comment]
```
blog.py:53: 
修改archives=Archive.all().order('-year').order('-month').fetch(12)
```

Original comment by `coolch...@gmail.com` on 21 Jan 2010 at 6:58

**Comment by GoogleCodeExporter** [comment]
Original comment by `coolch...@gmail.com` on 21 Jan 2010 at 6:59
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
- kind: Archive
  properties:
  - name: year
  - name: month
  - name: date

    direction: desc
```

Original comment by `snailb...@gmail.com` on 21 Jan 2010 at 7:23
